#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory

# moving Object mesh
echo "-----> START moving Object meshing"
(cd movingObjectMesh && ./Allrun.pre)
echo "-----> END moving Object meshing"

# Add background mesh and prepare case
echo "-----> START background meshing and case preparation"
(cd backgroundAndMovingObject && ./Allrun.pre)
echo "-----> END background meshing and case preparation"
#------------------------------------------------------------------------------
